before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: ensync-cli
    binary: ensync-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/rossi1/ensync-cli/pkg/version.Version={{.Version}}
      - -X github.com/rossi1/ensync-cli/pkg/version.Commit={{.Commit}}
      - -X github.com/rossi1/ensync-cli/pkg/version.BuildDate={{.Date}}

archives:
  - id: linux_darwin
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md
      - cmd/**/*
      - app/**/*
      - go.mod
      - go.sum
      - main.go
    builds:
      - ensync-cli
    format_overrides:
      - goos: windows
        format: zip

source:
  enabled: true
  name_template: '{{ .ProjectName }}_{{ .Version }}_source'
  format: 'zip'

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  draft: true
  prerelease: auto
  name_template: "v{{.Version}}"