name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'
          cache: true

      - name: Show Go Environment
        run: |
          go version
          go env
          pwd
          find . -name "go.mod"

      - name: Initialize Go Module
        run: |
          if [ ! -f go.mod ]; then
            go mod init github.com/yourusername/yourreponame
            go mod tidy
          fi

      - name: Download Dependencies
        run: go mod download

      - name: List files
        run: ls -al

      - name: Run Tests
        run: |
          go test -v -race ./...

      - name: Determine Next Version
        id: next_version
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
          major=$(echo $latest_tag | cut -d. -f1 | sed 's/v//')
          minor=$(echo $latest_tag | cut -d. -f2)
          patch=$(echo $latest_tag | cut -d. -f3)
          next_patch=$((patch + 1))
          next_version="v${major}.${minor}.${next_patch}"
          echo "Next version: $next_version"
          echo "next_version=$next_version" >> $GITHUB_ENV

      - name: Create and Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.next_version }}
          git push origin ${{ env.next_version }}

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          install-only: true

      - name: Run GoReleaser
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
