name: Auto Tag Release

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Generate and push new tag
        run: |
          # Fetch the latest tag, fallback to v0.0.1 if no tags exist
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.1")

          # Extract version numbers (major.minor.patch)
          IFS='.' read -r -a version_parts <<< "${latest_tag#v}"
          patch_version=$((version_parts[2] + 1))  # Increment the patch version
          new_tag="v${version_parts[0]}.${version_parts[1]}.$patch_version"  # Create new tag

          # Create the new tag and push it
          git tag -a "$new_tag" -m "Release version $new_tag"
          git push origin "$new_tag"  # Push the new tag to the remote repository

          echo "Created and pushed tag: $new_tag"
